create table usuario (
    id_usuario UUID PRIMARY KEY,
    nombre varchar(50),
    correo varchar(50),
    pass varchar(50),
    fecha_creacion datetime,
    fecha_modificacion datetime,
    fecha_ultimo_login datetime,
    token varchar(50),
    isactive boolean
)

create table telefono(
    id_telefono INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_usuario UUID,
    numero varchar(15),
    codigo_ciudad varchar(3),
    codigo_pais varchar(3),

    foreign key (id_usuario) references usuario(id_usuario)
)
